# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
baby_names=pd.read_csv("US_Baby_Names_right.csv")
baby_names

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Step 4. See the first 10 entries

In [3]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [6]:
baby_names.drop(columns=["Unnamed: 0","Id"],inplace=True)
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. What year has the highest number of baby names in the dataset?

In [25]:
# maxBabyCount=baby_names.Count.max()
# baby_names.loc[baby_names["Count"]==maxBabyCount,"Year"]

df=baby_names.groupby("Year").Count.sum()
df=df.to_frame()
print(df.Count.idxmax())

2007

### Step 7. Is there more male or female names in the dataset?

In [27]:
baby_names.Gender.value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 8. Group the dataset by name and assign to names

In [72]:
babygroup=baby_names.groupby("Name")["Name"].value_counts()
babygroup

Name
Aaban        2
Aadan        4
Aadarsh      1
Aaden      196
Aadhav       1
          ...
Zyra         7
Zyrah        2
Zyren        1
Zyria       10
Zyriah       9
Name: count, Length: 17632, dtype: int64

### Step 9. How many different names exist in the dataset?

In [39]:
# totalnames=pd.Series(baby_names.Name.unique())
# totalnames=totalnames.to_frame()
# totalnames.shape
print(f"total unique names : {baby_names.Name.unique().shape[0]}")

total unique names : 17632

### Step 10. What is the name with most occurrences?

In [49]:
mostCommonName=baby_names.Name.value_counts()
mostCommonName=mostCommonName.sort_values(ascending=False).to_frame()
mostCommonName.iloc[0]

count    1112
Name: Riley, dtype: int64

### Step 11. How many different names have the least occurrences?

In [59]:
mini=mostCommonName["count"].min()
mostCommonName[mostCommonName["count"]==mini]

           count
Name
Lizbett        1
Meeya          1
Mar            1
Mikela         1
Moorea         1
...          ...
Zailynn        1
Zailee         1
Dominga        1
Mohamadou      1
Coalton        1

[3682 rows x 1 columns]

### Step 12. What is the median name occurrence?

In [61]:
dfmid=baby_names.groupby("Name").Count.median()
dfmid=dfmid.to_frame()
dfmid

         Count
Name
Aaban      6.0
Aadan      5.5
Aadarsh    5.0
Aaden     10.0
Aadhav     6.0
...        ...
Zyra       6.0
Zyrah      5.5
Zyren      6.0
Zyria      6.0
Zyriah     6.0

[17632 rows x 1 columns]

### Step 13. What is the standard deviation of names?

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [63]:
baby_names["Name"].value_counts()

Name
Riley      1112
Avery      1080
Jordan     1073
Peyton     1064
Hayden     1049
           ...
Terryn        1
Yanna         1
Zemirah       1
Emmilyn       1
Coalton       1
Name: count, Length: 17632, dtype: int64