# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [2]:
dict1={
    "evolution" : ["Ivysaur","Charmeleon","Wartortle","Metapod"],
    "hp" : [45,39,44,45],
    "name" : ["Bulbasaur","Charmander","Squirtle","Caterpie"],
    "pokedex" : ["yes","no","yes","no"],
    "type" : ["grass","fire","water","bug"]
}

### Step 3. Assign it to a variable called pokemon

In [3]:
pokemon=pd.DataFrame(dict1)
pokemon

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2   Wartortle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [10]:
pokemon=pokemon[["name","type","hp","evolution","place"]]

### Step 5. Add another column called place, and insert what you have in mind.

In [11]:
pokemon["place"]=["mountain","forest","desert","grassland"]
pokemon

/var/folders/zs/9ycv0x2j3277bh0zqv6d2rd40000gn/T/ipykernel_83027/1305847698.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pokemon["place"]=["mountain","forest","desert","grassland"]

         name   type  hp   evolution      place
0   Bulbasaur  grass  45     Ivysaur   mountain
1  Charmander   fire  39  Charmeleon     forest
2    Squirtle  water  44   Wartortle     desert
3    Caterpie    bug  45     Metapod  grassland

### Step 6. Present the type of each column

In [12]:
pokemon.dtypes

name         object
type         object
hp            int64
evolution    object
place        object
dtype: object

### BONUS: Create your own question and answer it.

# Find the place of pokemon which has max hp.

In [9]:
pokemon.loc[pokemon["hp"]==pokemon["hp"].max(),"place"]

0     mountain
3    grassland
Name: place, dtype: object